# Generated by Django 5.1.2 on 2024-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
