# Generated by Django 5.1.2 on 2024-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
