# Generated by Django 5.1.2 on 2024-11-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_remove_file_file_file_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
